version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nodeapp:
    image: book_store-nodeapp:latest
    container_name: node_api
    restart: always
    env_file: .env
    ports:
      - "3001:3000"
    depends_on:
      - mysql
volumes:
  mysql_data:
